source 'https://rubygems.org'
gem 'net-ssh-simple', :git => 'https://github.com/GeoffWilliams/net-ssh-simple', :ref => 'pty_support'
gem 'puppetizer',
  :git => 'https://github.com/GeoffWilliams/puppetizer'
