# -*- mode: ruby -*-
# vi: set ft=ruby :

domain = "gitlab.demo.internal"
base_ip = "192.168.13.99"

Vagrant.configure("2") do |config|
  config.vm.box="puppetlabs/ubuntu-14.04-64-nocm"


  # common tasks for all hosts
  config.vm.provision "shell", inline: <<-SHELL
    # install handy tools
    sudo apt-get --assume-yes install curl openssh-server ca-certificates postfix
    curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
    sudo apt-get --assume-yes install gitlab-ce
    sudo gitlab-ctl reconfigure

  SHELL

    config.vm.network "private_network", ip: base_ip
    config.vm.hostname = domain

end
